#!/bin/bash

home=$(pwd)
std=${FSLDIR}/data/standard/MNI152_T1_2mm.nii.gz
stdMsk=${FSLDIR}/data/standard/MNI152_T1_2mm_brain_mask.nii.gz
dir=derivatives/stimZanalysis28032019
csv=$1 

# Functions

point() { #t1 #name
    # Create point in specific location in native map
    fslmaths $1 -mul 0 -add 1 -roi ${coords} $2 -odt float;
    fslmaths $2 -bin $2
}

normalization() { #inFile #outFile
    ANTS 3 -m CC[$std,$1,1,4] -i 50x20x10 -o $2 -t SyN[0.1,3,0]
}

warpAnts() { #inFile #outFile #Warp/Affine 
    WarpImageMultiTransform 3 $1 ${2}.nii.gz -R $std ${3}_Warp.nii.gz ${3}_Affine.txt

}

sphere() { #inFile #outFile
    # Create sphere
    fslmaths $1 -kernel sphere 2 -fmean -thr 0.001 -bin $2 -odt float;
}

cone() { #inFile #outFile
## Create cone shaped ROI for TMS FC

    # Create spheres for each size.
    fslmaths $1 -kernel sphere 2 -fmean -bin pre_sphere2mm -odt float;
    fslmaths $1 -kernel sphere 4 -fmean -bin pre_sphere4mm -odt float;
    fslmaths $1 -kernel sphere 7 -fmean -bin pre_sphere7mm -odt float;
    fslmaths $1 -kernel sphere 9 -fmean -bin pre_sphere9mm -odt float;
    fslmaths $1 -kernel sphere 12 -fmean -thr 0.001 -bin pre_sphere12mm -odt float;

    # Cut each sphere so they fit one inside the other.
    fslmaths pre_sphere12mm -sub pre_sphere9mm pre_sphere12mm -odt float;
    fslmaths pre_sphere9mm -sub pre_sphere7mm pre_sphere9mm -odt float;
    fslmaths pre_sphere7mm -sub pre_sphere4mm pre_sphere7mm -odt float;
    fslmaths pre_sphere4mm -sub pre_sphere2mm pre_sphere4mm -odt float;

    # Give intensities to each sphere.
    fslmaths pre_sphere2mm -mul 5 pre_sphere2mm -odt float;
    fslmaths pre_sphere4mm -mul 4 pre_sphere4mm -odt float;
    fslmaths pre_sphere7mm -mul 3 pre_sphere7mm -odt float;
    fslmaths pre_sphere9mm -mul 2 pre_sphere9mm -odt float;
    fslmaths pre_sphere12mm -mul 1 pre_sphere12mm -odt float;

    # Cut outside cortex.
    fslmaths pre_sphere2mm -mul $stdMsk pre_sphere2mm -odt float;
    fslmaths pre_sphere4mm -mul $stdMsk pre_sphere4mm -odt float;
    fslmaths pre_sphere7mm -mul $stdMsk pre_sphere7mm -odt float;
    fslmaths pre_sphere9mm -mul $stdMsk pre_sphere9mm -odt float;
    fslmaths pre_sphere12mm -mul $stdMsk pre_sphere12mm -odt float;

    # Combine masks.
    fslmaths pre_sphere2mm -add pre_sphere4mm -add pre_sphere7mm -add pre_sphere9mm -add pre_sphere12mm $2 -odt float;

    # Normalize intensity to 1
    fslmaths $2 -inm 1 ${2}Norm -odt float
  
    # Remove preliminary files
    rm pre* 
}



for i in $rids; do
    if [ -e ${dir}/${i}/*MNI2mm.nii.gz ]; then
        echo "$i is normalized already, moving on"
    else
        mkdir -p derivatives/ants/${i}
        cd ${dir}/${i}
        session $i
        t1w=derivatives/preproc_fsl/sub-${i}/ses-${sess}/reg/structural_head.nii.gz
        # ANTS
        ANTS 3 -m CC[$std2,$t1w,1,4] -i 50x20x10 -o ${i}_${sess}_MNI2mm_ -t SyN[0.1,3,0]
        # WarpImage
        WarpImageMultiTransform 3 $t1w ${i}_${sess}_MNI2mm.nii.gz -R $std2 ${i}_${sess}_MNI2mm_Warp.nii.gz ${i}_${sess}_MNI2mm_Affine.txt
        cd $home
    fi
done

#Body

while IFS="," read rid x y z ; do
    coords= "$x 1 $y 1 $z 1 0 1"
    t1w=${dir}/lin_correg/${rid}/vit/structural_head.nii.gz
    echo "#####"$rid"######"
    echo "##### Normalizing t1w #####"
    mkdir -p ${dir}/mni_norm/${rid}
    cd ${dir}/mni_norm/${rid}
    normalization $t1w ${rid}_2_mni
    cd $home

    echo "##### Making stim-point mask in native space #####"
    mkdir -p ${dir}/nativeStimPnt/${rid}
    cd ${dir}/nativeStimPnt
    point $t1w ${rid}nativePnt
    cd $home

    echo "##### Warping stim-point #####"
    mkdir -p ${dir}/mniStimSite
    cd ${dir}/mniStimSite
    warpAnts ${dir}/nativeStimPnt/${rid}nativePnt ${rid}mniPnt ${dir}/mni_norm/${rid}/${rid}_2_mni
    cd $home

    echo "##### Making stim-point spheres #####"
    mkdir -p ${dir}/coneSeeds
    cd ${dir}/coneSeeds
    sphere ${dir}/mniStimSite/${rid}mniPnt ${rid}mniSphere
    cone ${dir}/mniStimSite/${rid}mniPnt ${rid}mniCone
    cd $home
done < $csv
