#! /bin/bash
## SGE batch file - fmriprepTMS
#$ -S /bin/bash
#$ -N fmriprepTMS
## -t 1-35
#$ -V
#$ -l mem_free=18G
#$ -pe openmp 10
#$ -j y
#$ -wd /mnt/MD1200B/egarza/sfernandezl/logs/fmriprep

module load singularity/2.2

## sudo chmod 777 /mnt
# mkdir -p /mnt/MD1200B/egarza/sfernandezl/AddimexTMS/derivatives/fmriprep/output
export FS_LICENSE=/mnt/MD1200B/egarza/sfernandezl/freesurferLicense/license.txt
container=/mnt/MD1200B/egarza/sfernandezl/singImages/fmriprep20190725.img
subList=/mnt/MD1200B/egarza/sfernandezl/AddimexTMS/participants.tsv
sge_ndx=$(awk -v F='\t' -v OFS='\t' -v subIndx=$(($SGE_TASK_ID + 1)) 'NR==subIndx {print $1}' $subList)

# random sleep so that jobs dont start at _exactly_ the same time
sleep $(( $SGE_TASK_ID % 10 ))

singularity run -B /mnt:/mnt \
    $container \
    /mnt/MD1200B/egarza/sfernandezl/AddimexTMS \
    /mnt/MD1200B/egarza/sfernandezl/AddimexTMS/derivatives/fmriprep/output \
    participant \
    --participant-label ${sge_ndx} \
    --skip_bids_validation \
    --resource-monitor \
    --write-graph \
    --work-dir /mnt/MD1200B/egarza/sfernandezl/tmp \
    --output-space T1w template \
    --output-spaces T1w \
    --longitudinal \
    --use-syn-sdc;
